package title

import (
	"github.com/I82Much/rogue/static"
)

const (

	// generated by 	http://www.network-science.de/ascii/
	title = `

___________                         __________                             
\__    ___/__.__.______   __________\______   \ ____   ____  __ __   ____  
  |    | <   |  |\____ \_/ __ \_  __ \       _//  _ \ / ___\|  |  \_/ __ \ 
  |    |  \___  ||  |_> >  ___/|  | \/    |   (  <_> ) /_/  >  |  /\  ___/ 
  |____|  / ____||   __/ \___  >__|  |____|_  /\____/\___  /|____/  \___  >
          \/     |__|        \/             \/      /_____/             \/ 
		  
		Press
		  'e' for Easy
		  'm' for Medium
		  'h' for Hard
		  'i' for Insane
		  's' for Stenographer
		  'q' to Quit
`

	Easy = "START_EASY"
	Medium = "START_MEDIUM"
	Hard = "START_HARD"
	Insane = "START_INSANE"
	Stenographer = "START_STENOGRAPHER"
	Quit  = "QUIT"
)

func NewModule() *static.Module {
	return static.NewModule(title, map[rune]string{
		'e': Easy,
		'E': Easy,
		'm': Medium,
		'M': Medium,
		'h': Hard,
		'H': Hard,
		'i': Insane,
		'I': Insane,
		's': Stenographer,
		'S': Stenographer,
		'q': Quit,
		'Q': Quit,
	})
}
