package title

import (
	"github.com/I82Much/rogue/static"
)

const (

	// generated by 	http://www.network-science.de/ascii/ font stop
	title = `

    ______                          _______                        
   (_____ \                        (_______)                       
    _____) ) ___   ____ _   _  ____ _      _   _ ____   ____  ____ 
   (_____ ( / _ \ / _  | | | |/ _  ) |    | | | |  _ \ / _  )/ ___)
         | | |_| ( ( | | |_| ( (/ /| |____| |_| | | | ( (/ /| |    
         |_|\___/ \_|| |\____|\____)\______)__  | ||_/ \____)_|    
                 (_____|                  (____/|_|                
		  
* Explore the dungeon, fighting monsters with your typing skills.

* You must clear out each room before proceeding through to the next room. 

* During combat the object is to defend your player by typing the words that fall from
  the top of the screen. If the word reaches the red line, your player takes damage.

* In the attack phase of combat, you must type the word before it reaches the top
  line at the top of the screen.

Once you've cleared out every room of monsters, you'll win.

 Good luck!
		  
		Press
		  'e' for Easy         (15 wpm)
		  'm' for Medium       (40 wpm)
		  'h' for Hard         (70 wpm)
		  'i' for Insane       (100 wpm)
		  's' for Stenographer (300 wpm)
		  'q' to Quit
`
	Easy         = "START_EASY"
	Medium       = "START_MEDIUM"
	Hard         = "START_HARD"
	Insane       = "START_INSANE"
	Stenographer = "START_STENOGRAPHER"
	Quit         = "QUIT"
)

func NewModule() *static.Module {
	return static.NewModule(title, map[rune]string{
		'e': Easy,
		'E': Easy,
		'm': Medium,
		'M': Medium,
		'h': Hard,
		'H': Hard,
		'i': Insane,
		'I': Insane,
		's': Stenographer,
		'S': Stenographer,
		'q': Quit,
		'Q': Quit,
	})
}
