package gameover

import (
	"github.com/I82Much/rogue/static"
)

const (
	
	// generated by 	http://www.network-science.de/ascii/
	// font: stop
	title = `


    ______                       _____                   
   / _____)                     / ___ \                  
  | /  ___  ____ ____   ____   | |   | |_   _ ____  ____ 
  | | (___)/ _  |    \ / _  )  | |   | | | | / _  )/ ___)
  | \____/( ( | | | | ( (/ /   | |___| |\ V ( (/ /| |    
   \_____/ \_||_|_|_|_|\____)   \_____/  \_/ \____)_|    
                                                       
                                                

		  Press 'r' to restart or 'q' to quit
`

	Quit = "QUIT"
	Restart = "RESTART_GAME"
)

func NewModule() *static.Module {
	return static.NewModule(title, map[rune]string {
		'r': Restart,
		'R': Restart,
		'q': Quit,
		'Q': Quit,
	})
}